apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30100
  selector:
    app: greeting
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-grpc
  labels:
    app: greeting
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
      nodePort: 30101
  selector:
    app: greeting
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-prometheus
  labels:
    app: greeting
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: prometheus
      nodePort: 30104
  selector:
    app: greeting
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: 192.168.98.100:5000/greeting
          ports:
            - containerPort: 8000
              name: grpc
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: prometheus
