apiVersion: v1
kind: Service
metadata:
  name: greeting-api-doc
  labels:
    app: greeting-api-doc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30102
  selector:
    app: greeting-api-doc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting-api-doc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-api-doc
    spec:
      containers:
        - name: greeting-api-doc
          image: 192.168.98.100:5000/greeting-api-doc
          ports:
            - containerPort: 8080
              name: http
